### ISSUE TITLE
Configurable config.php values (also after inital install)

### ISSUE THREAD

**Issue by Gomez** [debops/ansible-owncloud#19]
I wanna make config.php values configurable: 

A sample config.php can look like this:

``` php
<?php
$CONFIG = array (
  'theme' => 'test',
  'trusted_domains' =>
  array (
    0 => 'owncloud.test.de',
  ),
  'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/var/www/virtual/xxx.portknox.net/htdocs/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 => 
    array (
      'path' => '/var/www/virtual/xxx.portknox.net/htdocs/apps2',
      'url' => '/apps2',
    ),
  ),

);
```

The theme option is easy, should be like this:

``` yml
  tasks:

    - name: switch theme
      lineinfile:
        dest=/var/www/owncloud/config/config.php
        regexp='theme'
        line=" 'theme' => {{ theme }},"
```

But how can i manage `trusted_domains` and `apps_paths`. They are more complex and multiline.  

Somewhere a example or can this be a way: http://stackoverflow.com/a/24345892/4046794
@drybjed @scibi @ypid
