### ISSUE TITLE
Support Nextcloud

### ISSUE THREAD

**Issue by ypid** [debops/ansible-owncloud#45]
Seems the NextCloud fork is doing great and will probably replace ownCloud in the future for good reasons. This role should be able to support both for now and in case ownCloud maintenance would be discontinued, the role should be renamed to `debops.nextcloud`.

~~Blockers for switching to NextCloud:~~
- [ ] No `.deb` packages available and upstream has no plans to provide them yet. See [#123](https://github.com/nextcloud/server/issues/123). In case nobody packages NextCloud then the best option would probably be to use the tar balls and check there GPG signature manually.

- [x] Going with tarballs for now.

I am currently not working on this. If anyone wants to give it a try, please go ahead.

Refs:
- https://nextcloud.com/beta-of-nextcloud-10-with-two-factor-authentication-improved-federation-and-more/
  Really nice stuff :wink:

**Comment by drybjed** [comment]
In case there will be no `.deb` packages available, I would prioritize getting the Nextcloud source from `git` instead of a tarball. Hopefully there will be some tags or even better, a "stable" branch or something similar? I suppose it also depends on what update mechanism will be included in the application itself.

**Comment by ypid** [comment]
@drybjed git would be possible as NextCloud does proper releases via tags and also fulfills the requirement of signing git tags: https://github.com/nextcloud/server/releases

I proposed to go with the tar balls because it is the default installation method. Related to: https://github.com/debops/ansible-owncloud/issues/37

Updates in NextCloud are supposed to happen by the self update mechanism. That could be evaluated again when implementing support but I would prefer to avoid that. Deployment should be handled automatically (see #28) and the NextCloud PHP app does not need write-access to it’s own source code that way.

**Comment by enoch85** [comment]
> what update mechanism

Here is an option: https://github.com/nextcloud/vm/blob/master/nextcloud_update.sh

**Comment by ypid** [comment]
@enoch85 Thanks for the pointer. It looks like this script is still effected by [Check downloaded files with GPG before using them](https://github.com/nextcloud/vm/issues/11) and can not be used directly therefore (ref: [Open Source software distributed as binary archives](https://docs.debops.org/en/latest/debops-policy/docs/software-source-policy.html#open-source-software-distributed-as-binary-archives)).

**Comment by enoch85** [comment]
So what you're saying is that the Nextcloud core updater should use GPG as well? It doesn't now afaik.

**Comment by ypid** [comment]
I guess that is why we prefer signed APT repos here. See above :wink: But I thought there was some checking going on in the NextCloud core updater. Will need to be checked.

**Comment by cryptofred** [comment]
The main problem here seems to be verifying and authenticating the downloaded tarballs before extracting them. Since the Nextcloud public key is on key servers now this should be an easy matter.

The question is, would you prefer to let Nextcloud update itself or let debops do it?

Wouldn't this suffice:
```
---
- hosts: debops_service_nextcloud
  become: true
  become_method: sudo
  tasks:
    - name: Create gnupg directory
      file:
        path: /root/.gnupg
        state: directory
        mode: 0600

    - name: Add Nextcloud PGP Key
      apt_key:
        id: "{{ nextcloud__pgp_fingerprint }}"
        keyring: /root/.gnupg/pubring.gpg
        keyserver: "{{ nextcloud__pgp_keyserver }}"
        state: present

    - name: Download Nextcloud tarball
      get_url:
        url: "{{ nextcloud__url }}/{{ nextcloud__tarball }}"
        dest: "/tmp/{{ nextcloud__tarball }}"
        mode: 0600

    - name: Download Nextcloud tarball checksum
      get_url:
        url: "{{ nextcloud__url }}/{{ nextcloud__tarball }}.sha256"
        dest: "/tmp/{{ nextcloud__tarball }}.sha256"
        mode: 0600

    - name: Download Nextcloud tarball signature
      get_url:
        url: "{{ nextcloud__url }}/{{ nextcloud__tarball }}.asc"
        dest: "/tmp/{{ nextcloud__tarball }}.asc"
        mode: 0600


    - name: Verify Nextcloud tarball integrity
      shell: "sha256sum -c {{ nextcloud__tarball }}.sha256"
      register: nextcloud__verify_integrity
      failed_when: nextcloud__verify_integrity.rc != 0
      args:
        chdir: /tmp


    - name: Verify Nextcloud tarball authenticity
      shell: "gpg --verify {{ nextcloud__tarball }}.asc 2>&1 | awk -F ':' 'END { gsub(\" \", \"\", $2); print $2}'"
      register: nextcloud__verify_authenticity
      failed_when: nextcloud__verify_authenticity.stdout != "{{ nextcloud__pgp_fingerprint }}"
      args:
        chdir: /tmp
```

With these variables:
```
nextcloud__pgp_fingerprint: "28806A878AE423A28372792ED75899B9A724937A",
nextcloud__pgp_keyserver: "pgp.mit.edu",
nextcloud__version: "11.0.3",
nextcloud__tarball: "nextcloud-{{ nextcloud__version }}.tar.bz2",
nextcloud__url: "https://download.nextcloud.com/server/releases"
```

?
